apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name hellosvc
  labels:
    app: *name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
    spec:
      containers:
        - image: docker.io/alexeldeib/hellosvc:dev
          imagePullPolicy: IfNotPresent
          name: *name
          envFrom:
            - secretRef:
                name: pg-config
          ports:
            - containerPort: 8080
              name: http
          resources: {}
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: &name hellosvc
  labels:
    app: *name
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: http
      targetPort: http
  selector:
    app: *name
---

