apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- manifests.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: tusker-schema
  files:
  - sql/schema.sql
- name: tusker-migrations
  files:
  - sql/migrations/foo